version: "3.8"

services:
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - node_modules:/workspace/node_modules
    ports:
      - "3000:3000"
      - "5173:5173"
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: sleep infinity

volumes:
  node_modules:
